/**
 *  本地存储的键
 */
const KEYS = {
  // 全局 featrues
  BACKGROUND: 'BACKGROUND',
  ENGINIE: 'ENGINIE',
  LOVESITES: 'LOVESITES',
  // 设置 - 搜索
  SETTING_SEARCH_YOUTUBE_TRANS : 'SETTING_SEARCH_YOUTUBE_TRANS',
  // 设置 - 模块
  SETTING_APPLICATION : 'SETTING_APPLICATION',
  SETTING_COMMONSITES : 'SETTING_COMMONSITES',
  // 设置 - 背景
  SETTING_BING: 'SETTING_BING',
  SETTING_COLOR: 'SETTING_COLOR'
}

export default KEYS
